-- ============================================================
-- RHSystem - Modelo MySQL
-- Baseado nas tabelas e campos presentes no arquivo RHSystem
-- ============================================================

CREATE DATABASE IF NOT EXISTS rh_system
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE rh_system;

-- ============================================================
-- LIMPEZA
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS BENEFICIOS_FUNCIONARIOS;
DROP TABLE IF EXISTS BENEFICIOS;
DROP TABLE IF EXISTS FORMULARIO_RESPOSTAS;
DROP TABLE IF EXISTS FORMULARIO_PERGUNTAS;
DROP TABLE IF EXISTS FORMULARIO;
DROP TABLE IF EXISTS TREINAMENTO_CERTIFICADO;
DROP TABLE IF EXISTS TREINAMENTO_FUNCIONARIO;
DROP TABLE IF EXISTS TREINAMENTO;
DROP TABLE IF EXISTS BANCO_HORAS;
DROP TABLE IF EXISTS ADVERTENCIA;
DROP TABLE IF EXISTS HOLERITE;
DROP TABLE IF EXISTS MANUTENCAO_PONTO;
DROP TABLE IF EXISTS PONTO;
DROP TABLE IF EXISTS AVISOS_VISUALIZACOES;
DROP TABLE IF EXISTS AVISOS;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS FUNCIONARIOS_DETALHES;
DROP TABLE IF EXISTS FUNCIONARIOS;
DROP TABLE IF EXISTS GESTORES;
DROP TABLE IF EXISTS SETORES;
DROP TABLE IF EXISTS CARGO;
DROP TABLE IF EXISTS NIVEIS_DE_ACESSO;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- 1. NIVEIS_DE_ACESSO
-- ============================================================

CREATE TABLE NIVEIS_DE_ACESSO (
    ID_NV_ACESSO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255)
) ENGINE=InnoDB;

-- ============================================================
-- 2. CARGO
-- ============================================================

CREATE TABLE CARGO (
    ID_CARGO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CARGO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    CARGA_HORARIA DECIMAL(5,2)
) ENGINE=InnoDB;

-- ============================================================
-- 3. FUNCIONARIOS
-- ============================================================
-- ID_GESTOR recebe FK posteriormente porque FUNCIONARIOS e
-- GESTORES possuem uma dependência circular no modelo.

CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DATA_NASCIMENTO DATE,
    DATA_ADMISSAO DATE NOT NULL,
    DATA_DESLIGAMENTO DATE,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(30),
    ID_CARGO INT,
    ID_SETOR INT,
    ID_GESTOR INT,
    ID_NV_ACESSO INT,

    CONSTRAINT FK_FUNCIONARIO_CARGO
        FOREIGN KEY (ID_CARGO)
        REFERENCES CARGO(ID_CARGO),

    CONSTRAINT FK_FUNCIONARIO_NIVEL_ACESSO
        FOREIGN KEY (ID_NV_ACESSO)
        REFERENCES NIVEIS_DE_ACESSO(ID_NV_ACESSO)
) ENGINE=InnoDB;

-- ============================================================
-- 4. SETORES
-- ============================================================
-- ID_GESTOR recebe FK posteriormente porque SETORES e GESTORES
-- também formam uma dependência circular.

CREATE TABLE SETORES (
    ID_SETOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    ID_GESTOR INT
) ENGINE=InnoDB;

-- ============================================================
-- 5. GESTORES
-- ============================================================

CREATE TABLE GESTORES (
    ID_GESTOR INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    ID_SETOR INT,
    ID_NV_ACESSO INT,

    CONSTRAINT FK_GESTOR_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),

    CONSTRAINT FK_GESTOR_SETOR
        FOREIGN KEY (ID_SETOR)
        REFERENCES SETORES(ID_SETOR),

    CONSTRAINT FK_GESTOR_NIVEL_ACESSO
        FOREIGN KEY (ID_NV_ACESSO)
        REFERENCES NIVEIS_DE_ACESSO(ID_NV_ACESSO)
) ENGINE=InnoDB;

-- ============================================================
-- 6. FKs que dependem de GESTORES
-- ============================================================

ALTER TABLE FUNCIONARIOS
    ADD CONSTRAINT FK_FUNCIONARIO_GESTOR
        FOREIGN KEY (ID_GESTOR)
        REFERENCES GESTORES(ID_GESTOR);

ALTER TABLE FUNCIONARIOS
    ADD CONSTRAINT FK_FUNCIONARIO_SETOR
        FOREIGN KEY (ID_SETOR)
        REFERENCES SETORES(ID_SETOR);

ALTER TABLE SETORES
    ADD CONSTRAINT FK_SETOR_GESTOR
        FOREIGN KEY (ID_GESTOR)
        REFERENCES GESTORES(ID_GESTOR);

-- ============================================================
-- 7. FUNCIONARIOS_DETALHES
-- ============================================================

CREATE TABLE FUNCIONARIOS_DETALHES (
    ID_FUNCIONARIO_DETALHES INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    NOME VARCHAR(150),
    DATA_NASCIMENTO DATE,
    DATA_ADMISSAO DATE,
    DATA_DESLIGAMENTO DATE,
    ATIVO BOOLEAN DEFAULT TRUE,
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(30),
    ID_CARGO INT,
    ID_NV_ACESSO INT,
    ID_GESTOR INT,

    CONSTRAINT FK_DETALHES_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),

    CONSTRAINT FK_DETALHES_CARGO
        FOREIGN KEY (ID_CARGO)
        REFERENCES CARGO(ID_CARGO),

    CONSTRAINT FK_DETALHES_NIVEL
        FOREIGN KEY (ID_NV_ACESSO)
        REFERENCES NIVEIS_DE_ACESSO(ID_NV_ACESSO),

    CONSTRAINT FK_DETALHES_GESTOR
        FOREIGN KEY (ID_GESTOR)
        REFERENCES GESTORES(ID_GESTOR)
) ENGINE=InnoDB;

-- ============================================================
-- 8. USUARIO
-- ============================================================

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    ULTIMO_LOGIN DATETIME,

    CONSTRAINT FK_USUARIO_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 9. AVISOS
-- ============================================================

CREATE TABLE AVISOS (
    ID_AVISO INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT,
    TITULO VARCHAR(200) NOT NULL,
    CONTEUDO TEXT NOT NULL,
    DATA_PUBLICACAO DATETIME,
    DATA_EXPIRACAO DATETIME,
    TIPO VARCHAR(50),

    CONSTRAINT FK_AVISO_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 10. AVISOS_VISUALIZACOES
-- ============================================================

CREATE TABLE AVISOS_VISUALIZACOES (
    ID_AVISO_VISUALIZACAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_AVISO INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    VISUALIZADO BOOLEAN NOT NULL DEFAULT FALSE,
    DATA_VISUALIZACAO DATETIME,

    CONSTRAINT FK_AVISO_VISUALIZACAO_AVISO
        FOREIGN KEY (ID_AVISO)
        REFERENCES AVISOS(ID_AVISO),

    CONSTRAINT FK_AVISO_VISUALIZACAO_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 11. PONTO
-- ============================================================

CREATE TABLE PONTO (
    ID_PONTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    DATA DATE NOT NULL,
    HORA_ENTRADA TIME,
    HORA_SAIDA TIME,
    HORAS_TRABALHADAS DECIMAL(5,2),
    CARGA_HORARIA DECIMAL(5,2),

    CONSTRAINT FK_PONTO_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 12. MANUTENCAO_PONTO
-- ============================================================

CREATE TABLE MANUTENCAO_PONTO (
    ID_MANUTENCAO_PONTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PONTO INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    JUSTIFICATIVA TEXT NOT NULL,
    DATA_SOLICITACAO DATETIME,
    STATUS VARCHAR(30),
    DATA_ANALISE DATETIME,
    ID_GESTOR INT,
    OBSERVACAO TEXT,

    CONSTRAINT FK_MANUTENCAO_PONTO
        FOREIGN KEY (ID_PONTO)
        REFERENCES PONTO(ID_PONTO),

    CONSTRAINT FK_MANUTENCAO_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),

    CONSTRAINT FK_MANUTENCAO_GESTOR
        FOREIGN KEY (ID_GESTOR)
        REFERENCES GESTORES(ID_GESTOR)
) ENGINE=InnoDB;

-- ============================================================
-- 13. HOLERITE
-- ============================================================

CREATE TABLE HOLERITE (
    ID_HOLERITE INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    MES TINYINT NOT NULL,
    ANO YEAR NOT NULL,
    DATA_PUBLICACAO DATETIME,
    ARQUIVO VARCHAR(255),

    CONSTRAINT FK_HOLERITE_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 14. ADVERTENCIA
-- ============================================================

CREATE TABLE ADVERTENCIA (
    ID_ADVERTENCIA INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    ID_GESTOR INT,
    DATA DATE,
    TIPO VARCHAR(50),
    MOTIVO VARCHAR(255),
    DESCRICAO TEXT,
    STATUS VARCHAR(30),

    CONSTRAINT FK_ADVERTENCIA_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),

    CONSTRAINT FK_ADVERTENCIA_GESTOR
        FOREIGN KEY (ID_GESTOR)
        REFERENCES GESTORES(ID_GESTOR)
) ENGINE=InnoDB;

-- ============================================================
-- 15. BANCO_HORAS
-- ============================================================

CREATE TABLE BANCO_HORAS (
    ID_BANCO_HORAS INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    DATA DATE,
    TIPO VARCHAR(30),
    QUANTIDADE DECIMAL(8,2),
    OBSERVACAO TEXT,

    CONSTRAINT FK_BANCO_HORAS_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 16. TREINAMENTO
-- ============================================================

CREATE TABLE TREINAMENTO (
    ID_TREINAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    DESCRICAO TEXT,
    TIPO VARCHAR(50),
    DATA_INICIO DATE,
    DATA_FIM DATE,
    OBRIGATORIO BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE=InnoDB;

-- ============================================================
-- 17. TREINAMENTO_FUNCIONARIO
-- ============================================================

CREATE TABLE TREINAMENTO_FUNCIONARIO (
    ID_TREIN_FUNC INT AUTO_INCREMENT PRIMARY KEY,
    ID_TREINAMENTO INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    STATUS VARCHAR(30),
    DATA_INICIO DATE,
    DATA_CONCLUSAO DATE,
    NOTA DECIMAL(5,2),

    CONSTRAINT FK_TREIN_FUNC_TREINAMENTO
        FOREIGN KEY (ID_TREINAMENTO)
        REFERENCES TREINAMENTO(ID_TREINAMENTO),

    CONSTRAINT FK_TREIN_FUNC_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 18. TREINAMENTO_CERTIFICADO
-- ============================================================

CREATE TABLE TREINAMENTO_CERTIFICADO (
    ID_CERTIFICADO INT AUTO_INCREMENT PRIMARY KEY,
    ID_TREINAMENTO INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    DATA_EMISSAO DATE,
    CODIGO_VALIDACAO VARCHAR(100),
    ARQUIVO VARCHAR(255),

    CONSTRAINT FK_CERTIFICADO_TREINAMENTO
        FOREIGN KEY (ID_TREINAMENTO)
        REFERENCES TREINAMENTO(ID_TREINAMENTO),

    CONSTRAINT FK_CERTIFICADO_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 19. FORMULARIO
-- ============================================================

CREATE TABLE FORMULARIO (
    ID_FORMULARIO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    DESCRICAO TEXT,
    TIPO VARCHAR(50),
    `ID_FUNCIONARIO (AUTOR)` INT,
    DATA_CRIACAO DATETIME,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT FK_FORMULARIO_AUTOR
        FOREIGN KEY (`ID_FUNCIONARIO (AUTOR)`)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 20. FORMULARIO_PERGUNTAS
-- ============================================================

CREATE TABLE FORMULARIO_PERGUNTAS (
    ID_FORMULARIO_PERGUNTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_FORMULARIO INT NOT NULL,
    ID_PERGUNTA INT,
    TEXTO_PERGUNTA TEXT NOT NULL,
    TIPO_RESPOSTA VARCHAR(50),
    ORDEM INT,
    `OBRIGATÓRIA` BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT FK_FORM_PERGUNTA_FORMULARIO
        FOREIGN KEY (ID_FORMULARIO)
        REFERENCES FORMULARIO(ID_FORMULARIO)
) ENGINE=InnoDB;

-- ============================================================
-- 21. FORMULARIO_RESPOSTAS
-- ============================================================
-- ID_PERGUNTA_PERGUNTA e ID_PERGUNTA foram mantidos porque
-- existem com esses nomes no modelo original.

CREATE TABLE FORMULARIO_RESPOSTAS (
    ID_FORMULARIO_RESPOSTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_FORMULARIO INT NOT NULL,
    ID_PERGUNTA_PERGUNTA INT,
    ID_PERGUNTA INT,
    ID_FUNCIONARIO INT NOT NULL,
    RESPOSTA TEXT,
    DATA_RESPOSTA DATETIME,

    CONSTRAINT FK_FORM_RESPOSTA_FORMULARIO
        FOREIGN KEY (ID_FORMULARIO)
        REFERENCES FORMULARIO(ID_FORMULARIO),

    CONSTRAINT FK_FORM_RESPOSTA_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),

    CONSTRAINT FK_FORM_RESPOSTA_PERGUNTA
        FOREIGN KEY (ID_PERGUNTA_PERGUNTA)
        REFERENCES FORMULARIO_PERGUNTAS(ID_FORMULARIO_PERGUNTA)
) ENGINE=InnoDB;

-- ============================================================
-- 22. BENEFICIOS
-- ============================================================

CREATE TABLE BENEFICIOS (
    ID_BENEFICIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255)
) ENGINE=InnoDB;

-- ============================================================
-- 23. BENEFICIOS_FUNCIONARIOS
-- ============================================================

CREATE TABLE BENEFICIOS_FUNCIONARIOS (
    ID_BENEFICIO_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    ID_BENEFICIO INT NOT NULL,
    POSSUI BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT FK_BENEFICIO_FUNCIONARIO_FUNCIONARIO
        FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),

    CONSTRAINT FK_BENEFICIO_FUNCIONARIO_BENEFICIO
        FOREIGN KEY (ID_BENEFICIO)
        REFERENCES BENEFICIOS(ID_BENEFICIO)
) ENGINE=InnoDB;

-- ============================================================
-- ÍNDICES AUXILIARES
-- ============================================================

CREATE INDEX IDX_FUNCIONARIOS_CARGO
    ON FUNCIONARIOS(ID_CARGO);

CREATE INDEX IDX_FUNCIONARIOS_SETOR
    ON FUNCIONARIOS(ID_SETOR);

CREATE INDEX IDX_FUNCIONARIOS_GESTOR
    ON FUNCIONARIOS(ID_GESTOR);

CREATE INDEX IDX_PONTO_FUNCIONARIO_DATA
    ON PONTO(ID_FUNCIONARIO, DATA);

CREATE INDEX IDX_HOLERITE_FUNCIONARIO_ANO_MES
    ON HOLERITE(ID_FUNCIONARIO, ANO, MES);

CREATE INDEX IDX_TREINAMENTO_FUNCIONARIO
    ON TREINAMENTO_FUNCIONARIO(ID_FUNCIONARIO);

CREATE INDEX IDX_BENEFICIOS_FUNCIONARIOS
    ON BENEFICIOS_FUNCIONARIOS(ID_FUNCIONARIO);

-- ============================================================
-- FIM DO SCRIPT
-- ============================================================
